frr version 8.0
hostname router-b
!
ip forwarding
!
router ospf
 ospf router-id 2.2.2.2
 ! On annonce le réseau local du Site B et le réseau WAN
 network 10.10.2.0/24 area 0
 network 172.20.0.0/27 area 0
!
line vty
!